VERSION="2.2.1"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=["GANGDZOHWSTLMLLCOONE3BE73CVAN3DB7OEIV455NV7Y5LPJSPKUIWZG"]

[DOCUMENTATION]
ORG_NAME="bullmanofficial"
ORG_DESCRIPTION="Beyond operating the world's leading cryptocurrency exchange, Stellar spans an entire ecosystem."
ORG_DBA="bullmanofficial.github.io"
ORG_URL="https://bullmanofficial.github.io"
ORG_LOGO= "https://bullmanofficial.github.io/favicon.png"
ORG_OFFICIAL_EMAIL="bullmanofficial@proton.me"

[[PRINCIPALS]]
name="bullmanofficial"
email="bullmanofficial@proton.me"
github="bullmanofficial"

[[CURRENCIES]]
code="BULLMAN"
status="live"
issuer="GANGDZOHWSTLMLLCOONE3BE73CVAN3DB7OEIV455NV7Y5LPJSPKUIWZG"
display_decimals=7
name="BULLMAN"
desc="Beyond operating the world's leading cryptocurrency exchange, Stellar spans an entire ecosystem."
conditions="Withdrawal fees apply"
image="https://bullmanofficial.github.io/img/BULLMAN.png"
is_asset_anchored=true
is_unlimited=false
anchor_asset="BULLMAN"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="BEARMAN"
status="live"
issuer="GANGDZOHWSTLMLLCOONE3BE73CVAN3DB7OEIV455NV7Y5LPJSPKUIWZG"
display_decimals=7
name="BEARMAN"
desc="Beyond operating the world's leading cryptocurrency exchange, Stellar spans an entire ecosystem."
conditions="Withdrawal fees apply"
image="https://bullmanofficial.github.io/img/BEARMAN.png"
is_asset_anchored=true
is_unlimited=false
anchor_asset="BEARMAN"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="xBULL"
status="live"
issuer="GANGDZOHWSTLMLLCOONE3BE73CVAN3DB7OEIV455NV7Y5LPJSPKUIWZG"
display_decimals=7
name="xBULL"
desc="Beyond operating the world's leading cryptocurrency exchange, Stellar spans an entire ecosystem."
conditions="Withdrawal fees apply"
image="https://bullmanofficial.github.io/img/XBULL.png"
is_asset_anchored=true
is_unlimited=false
anchor_asset="BULLMAN"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="XOGE"
status="live"
issuer="GANGDZOHWSTLMLLCOONE3BE73CVAN3DB7OEIV455NV7Y5LPJSPKUIWZG"
display_decimals=7
name="XOGE"
desc="Beyond operating the world's leading cryptocurrency exchange, Stellar spans an entire ecosystem."
conditions="Withdrawal fees apply"
image="https://bullmanofficial.github.io/img/XOGE.png"
is_asset_anchored=true
is_unlimited=false
anchor_asset="BULLMAN"
anchor_asset_type="crypto"
